name: Build and Deploy Angular App to Azure Static Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: GitHub'dan kodları çek
        uses: actions/checkout@v4

      - name: Node.js ortamını kur
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Angular bağımlılıklarını yükle
        run: npm install --legacy-peer-deps

      - name: Angular projesini production için derle
        run: npm run build -- --configuration production

      - name: Azure Static Web App'e dağıt
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/" # Angular kök klasörün
          output_location: "dist/dekofar-hyperconnect-panel" # Angular build çıktısının yolu
